### PR TITLE
Support for new deathworlders.com

### PR DESCRIPTION
**Pull request by Maocx**
These changes allow to follow the redirect to deathworlders.com and update the filter to reflect the changes on the site. This should fix the issue described in https://github.com/stonewalljones/hfyEbook/issues/7

### CODE REVIEW

**Comment by stonewalljones** [comment]
I'm going to test out these PRs and I should have them approved or feedback by Sunday

**Comment by Maocx** [comment]
Have you got the chance to look at the PRs yet? =)

**Comment by derjust** [comment]
I tested it, too - Actually i had to apply the fix from #7 on top of this PR:  61a22b2cad201bbe7be5c2a4b0eae810b01991ac 

Please feel free to update the PR or use my master:
Took also the liberty to extend the essential list: 18edad96b7309f066bb1ec03ef9118414a5754bb

**Comment by Maocx** [comment]
So, I worked on this some more:
 - Pulled in the changes of @derjust 
 - Correctly added the good training series to the essential reading order (included in this pr, sorry for mixing)
- Added support for the new format in which Hambone started posting the link on Reddit, starting from "Grounded" (https://www.reddit.com/r/HFY/comments/68ac07/ocjversethe_deathworlders_37_grounded/). A new filter is defined and follows the redirect to deathworlders.com
- Corrected the links for the waters of Babylon

These changes make the html version of the ebook 50% larger :D

**Pull request merged**
